--- Unused.
--- This was the module's own project roll dialog. Project rolls now go through
--- the game's own roll dialog via DTProjectEditor.PerformProjectRoll, which is
--- what brings titles, complications and kit modifiers to bear on them - none
--- of which this dialog could see. Its last caller was the roll button on the
--- character sheet's downtime tab, and that button is gone.
