--- @class TokenEffectLua Represents a token effect (teleport / transformation / destruction visual) registered by a mod.
--- @field id string The unique identifier of this token effect.
--- @field kind string The kind of effect: 'video' (a webm billboard) or 'particle' (a ParticleSystem from the TokenEffectIndex catalog).
--- @field video string For kind == 'video': the video asset path (e.g. 'teleport.webm').
--- @field playbackSpeed number Video playback speed multiplier. 1 = normal.
--- @field blend string Video blend mode: 'add' or 'alpha'.
--- @field hsv LuaVector4 HSV colour shift applied to a video effect.
--- @field particleName string For kind == 'particle': name of the ParticleSystem in TokenEffectIndex.particles.
--- @field worldSimulation boolean For kind == 'particle': force World simulation space so particles trail in place as the effect is moved (needed for a teleport travelEffect).
--- @field tint Color Tint colour applied to the effect.
--- @field scale number Scale multiplier applied on top of the per-call scale.
--- @field soundEvent string Optional sound-event id fed to audio.FireSoundEvent. Empty = silent.
--- @field duration number How long (seconds) the spawn site should wait before continuing.
--- @field delay number Delay (seconds) after the effect is triggered before it actually plays.
--- @field windup number Teleport only: seconds the token holds at the source location before it leaves.
--- @field travelTime number Teleport only: duration (seconds) of the invisible source-to-destination travel. 0 = instant.
--- @field travelEffect string Teleport only: id of another registered effect played on the token while it travels.
--- @field light table Optional light burst spawned alongside the effect (color / radius / duration).
TokenEffectLua = {}
